config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :flats do
    resources :reservations, only: [:new, :create]
    collection do
      get :dashboard
    end
  end
  resources :reservations, only: [:show, :destroy] do
    get :accept_status
    get :reject_status
    get :active_status
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  AMENITIES = ['wifi', 'television', 'car park', 'terrace', 'balcony', 'garden', 'patio', 'rooftop', 'stove', 'oven', 'kettle', 'micro-wave', 'coffee machine', 'dishwasher', 'washing machine', 'shower', 'bathtub', 'hot tub', 'bathroom towels', 'bathroom products', 'bed linen']
  belongs_to :user
  has_many :reservations, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 20 }
  validates :address, presence: true
  validates :availability_start, presence: true
  validates :availability_end, presence: true
  validates :number_of_guests, presence: true
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  validates :reservation_start, presence: true
  validates :reservation_end, presence: true
  validates :number_of_guests, presence: true
  # validate :end_date_is_after_start_date

  # private

  # def end_date_is_after_start_date
  #   if reservation_end < reservation_start
  #     errors.add(:reservation_end, 'cannot be before the start date')
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flats
  has_many :reservations
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  require 'json'

  def index
    if params[:query].present?
      @flats = Flat.where("address ILIKE ?", "%#{params[:query]}%")
      geocode(@flats)
    else
      @flats = Flat.all
      geocode(@flats)
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @reservation = Reservation.new

    @coordinates = @flat.geocode
    @marker = [{
      lat: @coordinates[0],
      lng: @coordinates[1],
      info_window: render_to_string(partial: "info_window", locals: { flat: @flat }),
      image_url: helpers.asset_url('flat.svg')
    }]

    availability(@flat)
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to dashboard_flats_path, notice: 'Flat created'
    else
      render 'flats/new'
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to dashboard_flats_path, notice: 'Flat updated successfully'
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to dashboard_flats_path, notice: 'Flat destroyed successfully'
  end

  def dashboard
    @flats = Flat.where(user_id: current_user)
    @reservations = Reservation.where(user_id: current_user)
  end

  private

  def flat_params
    params.require(:flat).permit(:title, :description, :address, :availability_start, :availability_end, :price_per_day, :number_of_guests, amenities: [], photos: [])
  end

  def geocode(flats)
    @markers = flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flat: flat }),
        image_url: helpers.asset_url('flat.svg')
      }
    end
  end

  def availability(flat)
    @flat_availability = Range.new(flat.availability_start, flat.availability_end).to_a
    @flat_reservation = []
    @flat.reservations.each do |reservation|
      unless reservation.status == "rejected"
        @flat_reservation << Range.new(reservation.reservation_start, reservation.reservation_end).to_a
      end
    end
    @flat_reservation.flatten!
    @flat_reservation.sort!
    @flat_availability -= @flat_reservation
    gon.flatavailability = @flat_availability
    gon.flatreservation = @flat_reservation
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def new
    @reservation = Reservation.new
    @user = current_user
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.flat = @flat
    # gon.reservationprice = @reservation.price
    if @reservation.save
      redirect_to dashboard_flats_path, notice: 'Reservation created'
    else
      redirect_to flat_path(@flat), notice: 'There is an error in the form'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
    @flat = Flat.find(@reservation.flat_id)
  end

  def accept_status
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.status = "accepted"
    @reservation.save!
    redirect_to dashboard_flats_path, notice: "Reservation accepted"
  end

  def reject_status
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.status = "rejected"
    @reservation.save!
    redirect_to dashboard_flats_path, notice: "Reservation rejected"
  end

  def active_status
    @reservation = Reservation.find(params[:reservation_id])
    @reservation.status = "active"
    @reservation.save!
    redirect_to dashboard_flats_path, notice: "Reservation active"
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to dashboard_flats_path, notice: 'Reservation destroyed successfully'
  end

  private

  def reservation_params
    params.require(:reservation).permit(:reservation_start, :reservation_end, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/flats/_info_window.html.erb
<% if controller_name == "flats" && action_name == "show" %>
  <h5><%= flat.title %></h5>
<% else %>
  <h4><%= flat.title %></h4>
  <p><%= flat.address %></p>
  <%= link_to flat_path(flat) do %>
      <p class="btn blue-btn">See more!</p>
  <% end %>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-6 rounded-container">
      <h2 class="mt-3">Update your flat</h2>
      <%= simple_form_for(@flat) do |f| %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :description, as: :text %>
        <%= f.input :availability_start, as: :string, input_html: {class: "datepicker"} %>
        <%= f.input :availability_end, as: :string, input_html: {class: "datepicker"} %>
        <%= f.input :price_per_day %>
        <%= f.input :number_of_guests %>
        <%= f.input :amenities, as: :check_boxes, collection: Flat::AMENITIES, input_html: { multiple: true } %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Update", class: "btn blue-btn" %>
      <% end %>
      <%= link_to "Back to dashboard", dashboard_flats_path, class: "btn lavander-btn mt-3" %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h2 class="mt-5">Choose your destination! 🚀</h2>
  <div class="d-flex justify-content-between row">
    <div class="search col-6">
      <%= form_tag flats_path, method: :get do %>
        <div class="d-flex align-items-center input-group">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id: "search-field",
            placeholder: "Where do you want to go?"
          %>
          <%= link_to flats_path do %>
          <button class="btn btn-light" type="button">X</button>
          <% end %>
        </div>
        <%= submit_tag "Search", class: "btn blue-btn mt-3" %>
      <% end %>
    </div>
    <div class="col-6 d-flex justify-content-end align-items-start">
      <%= link_to "Create a flat", new_flat_path, class: "btn pink-btn" %>
    </div>
  </div>
  <h2 class="mt-5">Browse the flats! 🏙️</h2>
  <div class="container-cards-index">
    <% if @flats.count.positive? %>
      <% @flats.each do |flat| %>
        <%= link_to flat_path(flat) do %>
          <div class="card-flat">
            <%= cl_image_tag flat.photos.first.key, class: "flat-image" %>
            <div class="card-flat-infos">
              <div class="card-flat-details">
                <h2><%= flat.title %></h2>
                <p><%= flat.address %></p>
              </div>
              <h2 class="card-flat-pricing"><%= flat.price_per_day %>€</h2>
            </div>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h5 style="color: white">Sorry, it seems that there are no flats matching your destination...😕</h5>
    <% end %>
  </div>
  <h2 class="mt-5">Browse the map! 🗺️</h2>
  <div id="geocoder" class="geocoder mt-2"></div>
  <div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" class="mt-3 mb-3"></div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-6 rounded-container">
      <h2 class="mt-3">Create a new flat</h2>
      <%= simple_form_for(@flat) do |f| %>
        <%= f.input :title %>
        <%= f.input :address %>
        <%= f.input :description, as: :text %>
        <%= f.input :availability_start, as: :string, input_html: {class: "datepicker"} %>
        <%= f.input :availability_end, as: :string, input_html: {class: "datepicker"} %>
        <%= f.input :price_per_day %>
        <%= f.input :number_of_guests %>
        <%= f.input :amenities, as: :check_boxes, collection: Flat::AMENITIES, input_html: { multiple: true } %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }, required: true %>
        <%= f.submit "Create a flat", class: "btn blue-btn" %>
      <% end %>
      <%= link_to "Back to flats", flats_path, class: "btn lavander-btn mt-3" %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container rounded-container">
  <div class="row mb-3 mt-3">
    <div class="col-12 p-0 d-flex justify-content-center">
      <div class="container-cards-show">
        <% @flat.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 200, width: 350, crop: :fill %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row mb-5 mt-5">
    <div class="col-6">
      <div class="card-flat-description-show">
        <h2><%= @flat.title %></h2>
        <p><%= @flat.description %></p>
        <p>Number of guests allowed: <%= @flat.number_of_guests %></p>
        <p id="price" data-price=<%= @flat.price_per_day%>>Price: <%= @flat.price_per_day %>€ per night</p>
        <p>Address: <%= @flat.address %></p>
        <p>Host: <%= @flat.user.first_name %> <%= @flat.user.last_name %></p>
        <% if @flat.amenities %>
          <p>Amenities:</p>
            <div class="pill-container">
            <% amenities = @flat.amenities.tr('["]','').split(',') %>
            <% amenities.shift %>
            <% amenities.each do |amenity| %>
              <p class="amenity-pill"><%= amenity %></p>
            <% end %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <% if current_user != @flat.user %>
        <h2>New reservation for <%= @flat.title %></h2>
        <p>Check the flat availability and choose your dates and number of guest(s)</p>
        <%= simple_form_for([@flat, @reservation]) do |f| %>
          <div class="d-flex align-items-center input-group">
            <%= f.input :reservation_start, as: :string, input_html: {class: "datepickerreservation form-control", value: @reservation_start }, required: true, hint: 'Cannot be blank. Reservation cannot start and end on the same day', label: "Arrival", placeholder: "Select date" %>
            <button class="btn btn-light" type="button" id="clear-btn-start" style="margin-bottom: 7px">X</button>
            <%= javascript_pack_tag 'clearflatpickr' %>
          </div>
          <div class="d-flex align-items-center input-group">
            <%= f.input :reservation_end, as: :string, input_html: {class: "datepickerreservation2 form-control", value: @reservation_end }, required: true, hint: 'Cannot be blank. Reservation cannot start and end on the same day',label: "Departure", placeholder: "Select date" %>
            <button class="btn btn-light" type="button" id="clear-btn-end" style="margin-bottom: 7px">X</button>
            <%= javascript_pack_tag 'clearflatpickr' %>
          </div>
          <div class="d-flex align-items-center">
            <%= f.input :number_of_guests, collection: 1..@flat.number_of_guests, required: true, input_html: {class: "numberofguests" }, hint: 'Cannot be blank' %>
            <button class="btn btn-light" type="button" id="clear-btn-guests" onclick="document.querySelector('.numberofguests').value=''" style="margin-bottom: 7px">X</button>
          </div>
          <div class="checkout-section"></div>
          <%= f.submit "Book the flat", class: "btn blue-btn"%>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="map"
        style="width: 100%; height: 400px;"
        data-markers="<%= @marker.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        class="mb-5 mt-5">
      </div>
  <%= link_to 'Back', :back, class: "btn lavander-btn" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlexFlat</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon(:init => true) %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://png.pngtree.com/thumb_back/fw800/back_pic/05/15/17/2459aab47adaad7.jpg);">
  <div class="container">
    <h2>Rent a Flat anywhere! 🏙️</h2>
    <p>Visit the world thanks to FlexFlat renting platform! 🌎</p>
    <%= link_to "Browse flats", flats_path, class: "btn blue-btn" %>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container">
  <h2>Reservation</h2>
  <% if current_user.id == @reservation.user.id %>
    <p>You have made a reservation for <%= @flat.title %> from <%= @reservation.reservation_start.strftime("%B %d %Y") %> to <%= @reservation.reservation_end.strftime("%B %d %Y") %>, please wait for <%= @flat.user.first_name %>'s confirmation.</p>
    <p>Status: <%= @reservation.status %></p>
  <% elsif current_user.id = @flat.user.id %>
    <p><%= @reservation.user.first_name %> <%= @reservation.user.last_name%> wants to book your flat from <%= @reservation.reservation_start.strftime("%B %d %Y") %> to <%= @reservation.reservation_end.strftime("%B %d %Y") %>.</p>
    <p>Status: <%= @reservation.status %></p>
    <%= link_to 'Accept', "#" %>
    <%= link_to 'Reject', "#" %>
  <% end %>
  <%= link_to "Back to flats", flats_path, class: "btn lavander-btn" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", alt: "logo" %>
  <% end %>

  <div>
    <%= link_to flats_path do %>
      <h1>FlexFlat</h1>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Browse flats", flats_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Create a flat", new_flat_path, class: "nav-link mr-3 text-white" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <% current_user_flat_reservations = [] %>
          <% if current_user.flats.present? %>
            <% current_user.flats.each do |flat| %>
              <% if flat.reservations.present? %>
                <% flat.reservations.each do |reservation| %>
                  <% current_user_flat_reservations << reservation.status %>
                <% end %>
              <% end %>
            <% end %>
            <% current_user_flat_reservations.each do |status| %>
              <% if status == "pending" %>
                <div class="notif avatar-notif"></div>
              <% end %>
            <% end %>
          <% end %>

          <% current_user_reservations = [] %>
          <% if current_user.reservations.present? %>
            <% current_user.reservations.each do |reservation| %>
              <% current_user_reservations << reservation.status %>
            <% end %>
            <% current_user_reservations.each do |status| %>
              <% if status == "pending" || status == "rejected" || status == "accepted" %>
                <div class="notif avatar-notif"></div>
              <% end %>
            <% end %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_flats_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>